### ISSUE TITLE
Add support for Vyper 0.4 Beta

### ISSUE THREAD

**Issue by anudit** [NomicFoundation/vyper-releases-mirror#12]
Hey @alcuadrado, Looks like the Actions have stopped updating due to inactivity, can we have support for the latest vyper [v0.4](https://github.com/vyperlang/vyper/releases/tag/v0.4.0b5) pre-releases?

Thanks!

**Comment by alcuadrado** [comment]
Sorry for the delay about this, and thanks for reporting it!
